-- MySQL Script generated by MySQL Workbench
-- Mon May 20 19:08:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema photos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photos` DEFAULT CHARACTER SET utf8 ;
USE `photos` ;

-- -----------------------------------------------------
-- Table `photos`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photos`.`USER` ;

CREATE TABLE IF NOT EXISTS `photos`.`USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photos`.`PHOTO_POST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photos`.`PHOTO_POST` ;

CREATE TABLE IF NOT EXISTS `photos`.`PHOTO_POST` (
  `POST_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `PHOTO_LINK` VARCHAR(200) NOT NULL,
  `USER_ID` INT NOT NULL,
  `DELETED` TINYINT NOT NULL,
  PRIMARY KEY (`POST_ID`),
  UNIQUE INDEX `POST_ID_UNIQUE` (`POST_ID` ASC) VISIBLE,
  INDEX `USER_ID_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `photos`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `photos`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `photos`;
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (101, 'Kubrick');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (102, 'Tarantino');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (103, 'Fincher');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (104, 'Formann');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (105, 'Cohan');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (106, 'Wright');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (107, 'Carpenter');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (108, 'Scott');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (109, 'Refn');
INSERT INTO `photos`.`USER` (`USER_ID`, `NAME`) VALUES (110, 'Snyder');

COMMIT;


-- -----------------------------------------------------
-- Data for table `photos`.`PHOTO_POST`
-- -----------------------------------------------------
START TRANSACTION;
USE `photos`;
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (1, 'Clockwork Orange', '2018-02-13 12:50:12', 'http://lightsup.ru/wp-content/uploads/2013/02/luchshie-postery-k-filmam-3.jpg', 101, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (2, 'Pulp Fiction', '2017-10-09 11:11:12', 'http://lightsup.ru/wp-content/uploads/2013/02/luchshie-postery-k-filmam-14.jpg', 102, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (3, 'Fight Club', '1998-04-02 20:20:01', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTridq2FkTN8Q112GU2e24DwwY7S_Ked8iykGdv54eoEClAap17', 103, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (4, 'One flew over...', '2016-01-20 19:33:23', 'https://www.buro247.kz/thumb/670x830_0/images/progression-of-best-picture-movie-posters-1.jpg', 104, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (5, 'Kill Bill', '1999-02-03 00:00:01', 'https://xage.ru/media/posts/2012/12/3/52-minimalisticheskih-postera-k-filmam_2.jpg', 102, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (6, 'The Big Lebowski', '1984-05-09 02:04:22', 'https://xage.ru/media/posts/2012/12/3/52-minimalisticheskih-postera-k-filmam_5.jpg', 105, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (7, 'Scott Piligrim', '2019-05-20 17:56:23', 'https://xage.ru/media/posts/2012/12/3/52-minimalisticheskih-postera-k-filmam_8.jpg', 106, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (8, 'The Thing', '1980-06-23 12:22:10', 'https://xage.ru/media/posts/2012/12/3/52-minimalisticheskih-postera-k-filmam_18.jpg', 107, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (9, 'Space Odyssey', '2001-10-10 13:35:26', 'https://xage.ru/media/posts/2012/12/3/52-minimalisticheskih-postera-k-filmam_21.jpg', 101, 0);
INSERT INTO `photos`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`, `DELETED`) VALUES (10, 'Blade Runner', '2008-09-09 23:11:10', 'https://xage.ru/media/posts/2012/12/3/52-minimalisticheskih-postera-k-filmam_22.jpg', 108, 0);

COMMIT;

